var constant = {
    //成功
    SUCCESS:"注册成功!",
    //账号为空
    USER_ACCOUNT_EMPTY:"账号为空!",
    //性别为空
    USER_SEX_EMPTY:"性别为空!",
    //地址为空
    USER_ADDRESS_EMPTY:"地址为空!",
    //出生年月日为空
    USER_BIRTHDAY_EMPTY:"出生年月日为空!",
    //身份证号码为空
    USER_ID_CARD_NUMBER_EMPTY:"身份证号码为空!",
    //电话号码为空
    USER_MOBILE_PHONE_EMPTY:"电话号码为空!",
    //用户已注册
    USER_IS_REGISTERED:"用户已注册!",
    //用户真实姓名为空
    USER_USERNAME_EMPTY:"用户真实姓名为空!",
    //用户密码为空
    USER_PASSWORD_EMPTY:"用户密码为空!",
    //用户登录成功
    LOGIN_SUCCESS:"用户登录成功!",
    //用户不存在
    USER_NOT_EXIST:"用户不存在!",
    //密码错误
    PASSWORD_ERROR:"密码错误!",
};