/* 2016-08-03 13:27:51 j.zhou */
(function(){function m(b){"string"==typeof b&&(b=c.getElementById(b));return b}function l(b,c,a){e.addEventListener?b.addEventListener(c,a,!1):e.attachEvent&&b.attachEvent("on"+c,function(){a.call(b,e.event)})}function p(b,c){b.className.match(RegExp("(\\s|^)"+c+"(\\s|$)"))||(b.className+=" "+c)}function g(b,c){b.className=b.className.replace(RegExp("(\\s|^)"+c+"(\\s|$)")," ")}function h(b){if(!b.pageX&&b.clientX){var a=1,f=document.body;f.getBoundingClientRect&&(a=f.getBoundingClientRect(),a=(a.right-
a.left)/f.clientWidth);return{x:b.clientX/a+c.body.scrollLeft+c.documentElement.scrollLeft,y:b.clientY/a+c.body.scrollTop+c.documentElement.scrollTop}}return{x:b.pageX,y:b.pageY}}var c=document,e=window,a=function(){var b=c.createElement("div");return function(c){b.innerHTML=c;c=b.childNodes[0];b.removeChild(c);return c}}(),f=document.documentElement.getBoundingClientRect?function(b){var c=b.getBoundingClientRect(),a=b.ownerDocument;b=a.body;var a=a.documentElement,f=a.clientTop||b.clientTop||0,d=
a.clientLeft||b.clientLeft||0,e=1;b.getBoundingClientRect&&(e=b.getBoundingClientRect(),e=(e.right-e.left)/b.clientWidth);1<e&&(d=f=0);return{top:c.top/e+(window.pageYOffset||a&&a.scrollTop/e||b.scrollTop/e)-f,left:c.left/e+(window.pageXOffset||a&&a.scrollLeft/e||b.scrollLeft/e)-d}}:function(b){if(e.jQuery)return jQuery(b).offset();var c=0,a=0;do c+=b.offsetTop||0,a+=b.offsetLeft||0;while(b=b.offsetParent);return{left:a,top:c}},d=function(){var b=0;return function(){return"ValumsAjaxUpload"+b++}}(),
k=function(){var b;return function(){if(b)return b;if("undefined"!==typeof XMLHttpRequest)b=new XMLHttpRequest;else for(var c=["Microsoft.XmlHttp","MSXML2.XmlHttp.5.0","MSXML2.XmlHttp.4.0","MSXML2.XmlHttp.3.0","MSXML2.XmlHttp.2.0"],a=0;a<c.length;a++)try{b=new ActiveXObject(c[a]);break}catch(f){}return b}}();Ajax_upload=AjaxUpload=function(b,a){b.jquery?b=b[0]:"string"==typeof b&&/^#.*/.test(b)&&(b=b.slice(1));b=m(b);this._input=null;this._button=b;this._justClicked=this._submitting=this._disabled=
!1;this._parentDialog=c.body;this._type="ontouchstart"in document.documentElement;if(window.jQuery&&jQuery.ui&&jQuery.ui.dialog){var f=jQuery(this._button).parents(".ui-dialog");f.length&&(this._parentDialog=f[0])}this._settings={action:"upload.php",name:"userfile",data:{type:"journals",typeID:13,token:"78A566F2-AA8A-4C4C-8EE8-F99FB3D4A1D8",randomKey:+new Date},autoSubmit:!0,responseType:!1,closeConnection:"",hoverClass:"hover",onChange:function(b,c){},onSubmit:function(b,c){},onComplete:function(b,
c){}};for(var d in a)this._settings[d]=a[d];this._createInput();this._type||this._rerouteClicks()};AjaxUpload.prototype={setData:function(b){this._settings.data=b},disable:function(){this._disabled=!0},enable:function(){this._disabled=!1},destroy:function(){this._input&&(this._input.parentNode&&this._input.parentNode.removeChild(this._input),this._input=null)},_createInput:function(){var b=this,a=c.createElement("input");a.setAttribute("type","file");a.setAttribute("name",this._settings.name);var f=
{position:"absolute",margin:"-5px 0 0 -175px",padding:0,width:"220px",height:"30px",fontSize:"14px",opacity:0,cursor:"pointer",display:"none",zIndex:2147483583},d;for(d in f)a.style[d]=f[d];"0"!==a.style.opacity&&(a.style.filter="alpha(opacity=0)");this._parentDialog.appendChild(a);l(a,"change",function(){var a=this.value.replace(/.*(\/|\\)/,"");!1!=b._settings.onChange.call(b,a,/[.]/.exec(a)?/[^.]+$/.exec(a.toLowerCase()):"")&&b._settings.autoSubmit&&b.submit()});l(a,"click",function(){b.justClicked=
!0;setTimeout(function(){b.justClicked=!1},2500)});this._input=a;this._type&&this._pad()},_pad:function(){$(this._button).html($(this._input).attr("style","").css({opacity:0,width:"100%",height:"100%",display:"block",margin:"0 0 0 -20px"}))},_rerouteClicks:function(){var b,a,d,e,k=this,m={top:0,left:0},q=!1;l(k._button,"mouseover",function(g){if(k._input&&!q){q=!0;g=k._button;var s,h,l;h=f(g);s=h.left;l=h.top;h=s+g.offsetWidth;b=s;a=h;d=l;e=l+g.offsetHeight;k._parentDialog!=c.body&&(m=f(k._parentDialog))}});
l(document,"mousemove",function(c){var f=k._input;if(f&&q)if(k._disabled)g(k._button,k._settings.hoverClass),f.style.display="none";else if(c=h(c),c.x>=b&&c.x<=a&&c.y>=d&&c.y<=e)f.style.top=c.y-m.top+"px",f.style.left=c.x-m.left+"px",f.style.display="block",p(k._button,k._settings.hoverClass);else{q=!1;var l=setInterval(function(){k.justClicked||(q||(f.style.display="none"),clearInterval(l))},25);g(k._button,k._settings.hoverClass)}})},_createIframe:function(){var b=d(),f=a('<iframe src="javascript:false;" name="'+
b+'" />');f.id=b;f.style.display="none";c.body.appendChild(f);return f},submit:function(){var b=this,a=this._settings;if(""!==this._input.value){var f={name:this._input.value.replace(/.*(\/|\\)/,""),id:d()};if(!1!=a.onSubmit.call(this,f,/[.]/.exec(f.name)?/[^.]+$/.exec(f.name.toLowerCase()):"")){var e=this._createIframe(),g=this._createForm(e);g.appendChild(this._input);if(a.closeConnection&&/AppleWebKit|MSIE/.test(navigator.userAgent)){var h=k();h.open("GET",a.closeConnection,!1);h.send("")}g.submit();
c.body.removeChild(g);this._input=g=null;this._createInput();var m=!1;l(e,"load",function(d){if("javascript:'%3Chtml%3E%3C/html%3E';"==e.src||"javascript:'<html></html>';"==e.src)m&&setTimeout(function(){c.body.removeChild(e)},0);else if(d=e.contentDocument?e.contentDocument:frames[e.id].document,!d.readyState||"complete"==d.readyState)if(!d.body||"false"!=d.body.innerHTML){var g;d.XMLDocument?g=d.XMLDocument:d.body?(g=d.body.innerHTML,a.responseType&&"json"==a.responseType.toLowerCase()&&(d.body.firstChild&&
"PRE"==d.body.firstChild.nodeName.toUpperCase()&&(g=d.body.firstChild.firstChild.nodeValue),g=g?window.eval("("+g+")"):{})):g=d;a.onComplete.call(b,f,g);m=!0;e.src="javascript:'<html></html>';"}})}else c.body.removeChild(this._input),this._input=null,this._createInput()}},_createForm:function(b){var f=this._settings,d=a('<form method="post" enctype="multipart/form-data"></form>');d.style.display="none";d.action=f.action;d.target=b.name;c.body.appendChild(d);for(var e in f.data)b=c.createElement("input"),
b.type="hidden",b.name=e,b.value=f.data[e],d.appendChild(b);return d}}})();
(function(m,l){function p(){this.ajaxu={};this.type=this.checkflash().pv[0]?"swf":"ajax"}p.prototype.checkflash=function(){var g=window,h=document,c=navigator,h="undefined"!=typeof h.getElementById&&"undefined"!=typeof h.getElementsByTagName&&"undefined"!=typeof h.createElement,e=c.userAgent.toLowerCase(),a=c.platform.toLowerCase(),f=a?/win/.test(a):/win/.test(e),a=a?/mac/.test(a):/mac/.test(e),e=/webkit/.test(e)?parseFloat(e.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,d=!+"\v1",k=[0,0,0],b=null;
if("undefined"!=typeof c.plugins&&"object"==typeof c.plugins["Shockwave Flash"])!(b=c.plugins["Shockwave Flash"].description)||"undefined"!=typeof c.mimeTypes&&c.mimeTypes["application/x-shockwave-flash"]&&!c.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(plugin=!0,d=!1,b=b.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),k[0]=parseInt(b.replace(/^(.*)\..*$/,"$1"),10),k[1]=parseInt(b.replace(/^.*\.(.*)\s.*$/,"$1"),10),k[2]=/[a-zA-Z]/.test(b)?parseInt(b.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=
typeof g.ActiveXObject)try{var l=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");l&&(b=l.GetVariable("$version"))&&(d=!0,b=b.split(" ")[1].split(","),k=[parseInt(b[0],10),parseInt(b[1],10),parseInt(b[2],10)])}catch(m){}return{w3:h,pv:k,wk:e,ie:d,win:f,mac:a}};p.prototype.upload=function(g){if("swf"===this.type)this.ajaxu=new SWFUpload(g);else{document.domain=g.domain;var h=document.getElementById(g.button_placeholder_id);l("#"+g.button_placeholder_id).css({width:g.button_width,height:g.button_height,
background:"url("+g.button_image_url+") 0 0 no-repeat"}).html("");this.ajaxu=new AjaxUpload(h,{action:g.upload_url,data:g.post_params,onSubmit:function(c,e){if(!e&&/^(jpg|jpeg|png)$/.test(e))return alert("\u65e0\u6548\u7684\u6587\u4ef6\u540d"),!1;g.file_queued_handler.call(this,c);return!0},onComplete:function(c,e){g.upload_success_handler.call(this,c,e)}})}return this.ajaxu};p.prototype.formatdata=function(g){g=(new Function("return "+g.replace(/(<script)+[^<>]*>[^\0]*(<\/script>)+/gm,"")))();return"undefined"!=
typeof g.error&&""==g.error?g.data[0]:""};window.gs_upload=p})(window,jQuery);
$(function(){var m=INTERFACE.poiType,l="\u65c5\u884c\u4e2d\u6709\u54ea\u4e9b\u4eae\u70b9\uff1f\u54ea\u4e9b\u53d1\u73b0\uff1f\u7ed9\u8ff7\u832b\u7684\u6e38\u53cb\u4eec\u6307\u6761\u660e\u8def\u5427~";3==m?l="\u5473\u9053\u5982\u4f55\uff1f\u670d\u52a1\u597d\u4e0d\uff1f\u5404\u79cd\u7f8e\u5473\uff0c\u5404\u79cd\u53e3\u6c34\uff0c\u6709\u6728\u6709\uff1f":4==m&&(l="\u8d27\u8272\u5982\u4f55\uff1f\u670d\u52a1\u600e\u6837\uff1f\u5404\u79cd\u8840\u62fc\uff0c\u5404\u79cd\u62d4\u8349\uff0c\u6709\u6728\u6709\uff1f");$(".form_side dd").each(function(){60<
$(this).height()&&$(this).parent().siblings(".morelink").show()});$(".form_side .morelink").click(function(){var c=$(this);if("\u66f4\u591a"==$(this).text()){var e=c.siblings("dl").find("dd").outerHeight(),e=parseInt(e,10)+27;c.siblings("dl").css({"max-height":e});c.text("\u6536\u8d77")}else c.siblings("dl").css({"max-height":"87px"}),c.text("\u66f4\u591a")});$(".formnotice .close").click(function(){$(this).parent().slideUp("slow")});var p=["\u5f88\u5dee","\u5dee","\u4e00\u822c","\u597d","\u5f88\u597d"],
g=null!=navigator.userAgent.match(/iPad/i);(function(){function c(b){b.addClass("hovered");b.prevAll().addClass("hovered");f.hide();d.hide();a.show();a.html(p[b.index()])}function e(b){b.removeClass("hovered");b.siblings().removeClass("hovered");a.hide();$(".sringbox .c_ring_large i").hasClass("selected")||f.show()}var a=$(".form_line .sringbox").siblings(".changecomment"),f=$(".form_line .sringbox").siblings(".sringtext"),d=$(".form_line .sringbox").siblings(".error_text"),k=$(".sringbox .c_ring_large i");
k.on("click",function(){var b=$(".sringbox .c_ring_large");b.find("i").removeClass("selected");var a=$(this).index()+1;b.find("i:lt("+a+")").addClass("selected")});if(g)k.on("touchstart",function(){c($(this))}).on("touchend",function(){e($(this))});else k.hover(function(){c($(this))},function(){e($(this))})})();(function(){function c(a){a.addClass("hovered");a.prevAll().addClass("hovered");var c=a.parent().siblings(".changecomment");c.show();c.html(p[a.index()])}function e(a){a.removeClass("hovered");
a.siblings().removeClass("hovered");a.parent().siblings(".changecomment").hide()}var a=$(".catecomment .c_ring_middle i");a.on("click",function(){$(this).parent().find("i").removeClass("selected");var a=$(this).index()+1;$(this).parent().find("i:lt("+a+")").addClass("selected")});if(g)a.on("touchstart",function(){c($(this))}).on("touchend",function(){e($(this))});else a.hover(function(){c($(this))},function(){e($(this))})})();(function(){var c=$(".review_content textarea"),e=$(".review_content .bottomtips em"),
a=$(".review_content .bottomtips .f_right");c.placeholder();c.gsInputLen(function(f){var d=1E3-f;0<f&&30>f&&(d=30-f,a.html("\u6700\u5c1130\u4e2a\u5b57\uff0c\u4f60\u8fd8\u9700\u8981\u8f93\u5165<em>"+d+"</em>\u5b57\uff0c\u5c06\u83b7\u5f97\u79ef\u5206\uff01"));30<f&&60>f&&(d=60-f,a.html("\u518d\u5199<em>"+d+"</em>\u4e2a\u5b57\u5e76\u4f20\u56fe\uff0c\u6210\u4e3a\u4f18\u8d28\u70b9\u8bc4\uff0c\u83b7\u5f97\u66f4\u591a\u79ef\u5206\uff01"));60<f&&1E3>f&&(d=1E3-f,a.html("\u4f60\u8fd8\u53ef\u4ee5\u5199<em>"+
d+"</em>\u4e2a\u5b57\uff0c\u68d2\u68d2\u54d2\uff01"));""==$.trim(c.val())&&(d=10,a.html("\u518d\u5199<em>"+d+"</em>\u4e2a\u5b57\u5e76\u4f20\u56fe\uff0c\u6210\u4e3a\u4f18\u8d28\u70b9\u8bc4\uff0c\u83b7\u5f97\u66f4\u591a\u79ef\u5206\uff01"));-1>=d?(f=$.trim(c.val()),f=$.gsSubstring(f,1E3,1),c.val(f),e.html(0)):(c.val()==l&&(d=10,a.html("\u518d\u5199<em>"+d+"</em>\u4e2a\u5b57\u5e76\u4f20\u56fe\uff0c\u6210\u4e3a\u4f18\u8d28\u70b9\u8bc4\uff0c\u83b7\u5f97\u66f4\u591a\u79ef\u5206\uff01")),e.html(d))});c.triggerHandler("focus");
c.focus(function(){$(".review_content .bottomtips .error_text").hide()})})();$(".form_line .youcate li").click(function(){$(".form_line .youcate li").removeClass("current");$(this).addClass("current");$(".form_line .youcate").siblings(".bottomtips").find(".error_text").hide()});$("#selectMonth").css("z-index","2");$(".form_line .gsn-select").hover(function(){var c=$(this);c.children("ul").show();c.children("span").addClass("arrow-cur")},function(){var c=$(this);c.children("ul").hide();c.children("span").removeClass("arrow-cur")});
$(".form_line .gsn-select a").click(function(){var c=$(this);c.parents(".gsn-select").find(".select-txt").html(c.html()).addClass("select-txt-cur");c.parents("ul").hide();var e=c.parents(".f_rbox").find("#selectYear .select-txt"),a=c.parents(".f_rbox").find("#selectMonth .select-txt"),f=c.parents(".f_rbox").find("#selectHour .select-txt");0<f.length?(c="\u5929"==f.html()?"\u5c0f\u65f6":"\u5929",f.siblings(".selectlist").find("li a").html(c)):"\u5e74"!=e.html()&&"\u6708"!=a.html()&&c.parents(".f_rbox").find(".error_text").hide()});
var h=null;$(".form_line .verification_input").focus(function(){clearTimeout(h);$(this).parents(".f_rbox").find(".error_text").hide()});$(".form_line .verification_input").bind("paste blur keyup",function(){var c=$(this);h=setTimeout(function(){var e=c.val(),e=e.replace(/^0+|[^\d]/g,"");c.val(e)},50)});$(".form_line .gsn-btn-20").click(function(){if(!$(this).hasClass("a_popup_login")){var c=!0,e=$(".form_line .c_ring_large i.selected").length;0===e&&(c=!1,$(".form_line .sringbox").siblings(".sringtext").hide(),
$(".form_line .sringbox").siblings(".error_text").show());var a=parseInt($(".review_content .bottomtips em").html(),10),f=$(".review_content textarea").val(),f=GS.xssFilter(f),f=$.trim(f);if(980<a||$(".review_content textarea").val()==l)c=!1,$(".review_content .bottomtips .error_text").show();0===$(".form_line .youcate li.current").length&&(c=!1,$(".form_line .youcate").siblings(".bottomtips").find(".error_text").show());var d=$(".form_line[data-poi-type='attractions']"),g,b,h,m;if(0<d.length){var a=
d.find("#selectYear .select-txt"),n=d.find("#selectMonth .select-txt");h=d.find(".verification_input");m=h.parents(".form_line").find(".select-txt").text();g=a.html().replace("\u5e74","");b=n.html().replace("\u6708","");h=parseFloat(h.val())}var d=$(".form_line[data-poi-type='restaurant']"),p,u,q;0<d.length&&(a=d.find("#selectYear .select-txt"),n=d.find("#selectMonth .select-txt"),p=a.html().replace("\u5e74",""),u=n.html().replace("\u6708",""),q=d.find(".verification_input").val());var n=$(".form_line[data-poi-type='shop']"),
v,s;0<n.length&&(a=n.find("#selectYear .select-txt"),n=n.find("#selectMonth .select-txt"),v=a.html().replace("\u5e74",""),s=n.html().replace("\u6708",""));if(c){$(this).gsdisable({time:6E3,disable:"gsn-btn-20 not_clickable",callback:function(){}});var n=$(".form_line .catecomment"),c=n.eq(0),a=n.eq(1),n=n.eq(2),t="";$(".upload_ul li").each(function(){var a=$(this).attr("data-img-id");t+=a+","});e={j_jingse:n.find("li:eq(0)").find("i.selected").length,j_quwei:n.find("li:eq(1)").find("i.selected").length,
j_xingjiabi:n.find("li:eq(2)").find("i.selected").length,j_year:g,j_month:b,j_length:h,j_length_type:m,c_kouwei:c.find("li:eq(0)").find("i.selected").length,c_huanjing:c.find("li:eq(1)").find("i.selected").length,c_fuwu:c.find("li:eq(2)").find("i.selected").length,c_year:p,c_month:u,c_xiaofei:q,s_shangpin:a.find("li:eq(0)").find("i.selected").length,s_huanjing:a.find("li:eq(1)").find("i.selected").length,s_fuwu:a.find("li:eq(2)").find("i.selected").length,s_year:v,s_month:s,zongti:e,content:f,imgs:t.substring(0,
t.length-1),travelType:$(".form_line .youcate li.current").index()};INTERFACE.publishFn(e)}}})});var gsupload={};
$(function(){function m(){"swf"==gsupload.type&&$.browser.msie&&gsupload.setButtonImageURL(e)}function l(a){a.find("i.delete").click(function(){a.remove();m();a.attr("data-img-id")})}function p(a,c){if(10<=$(".upload_ul li").length)$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\uff0c\u6700\u591a\u53ea\u53ef\u4e0a\u4f2010\u5f20\u7167\u7247\u3002</p>'});else{for(var d=a.name,e=0,e=d.replace(/\s/ig,"x").replace(/[^x00-xff]/g,"xx").length,b="",g=0,e=e-10;e<d.length&&!(128<d.charCodeAt(e)?
g+=2:g++,b+=d.charAt(e),10<=g);e++);d="..."+b;b=[];b.push('<li data-type="error">');b.push(' <i class="failed"></i>');b.push(' <i class="delete"></i>');b.push(' <span class="file-name">'+d+"</span>");b.push(' <span class="error-msg">'+c+"</span>");b.push("</li>");b=$(b.join(""));$(".upload_ul").append(b);l(b);m()}}var g=$("#gs_uploadurl").val();$("#imgRootPath").val();var h=!0,c=$.browser.msie?101:100,e=INTERFACE.upload_btn_domain+"/comment/img/comment_upload.png";gsupload=new gs_upload;g={domain:g.replace(/http:\/\/.*?\.(.*?)\/.*/ig,
"$1"),upload_url:g,flash_url:function(a){re=/(.*\/)/ig;r=a.match(re);return r[0]+"images/swfupload_fp9.swf"}(g),file_types:"*.jpg;*.png;",file_size_limit:"10MB",file_queue_limit:10,button_placeholder_id:"uploadBtn",button_image_url:e,button_width:c,button_height:30,WINDOW_MODE:{WINDOW:"window",OPAQUE:"opaque"},debug:!1,prevent_swf_caching:!1,preserve_relative_urls:!1,button_action:SWFUpload.BUTTON_ACTION.SELECT_FILES,button_cursor:SWFUpload.CURSOR.HAND,button_disabled:!1,post_params:{typeID:13,type:"journals",
token:"78A566F2-AA8A-4C4C-8EE8-F99FB3D4A1D8",randomKey:+new Date},file_queue_error_handler:function(a,c,d){try{switch($(".upload_ul").find("li[data-type='error']").remove(),h=!1,c){case SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED:$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\uff0c\u6700\u591a\u53ea\u53ef\u4e0a\u4f205\u5f20\u7167\u7247\u3002</p>'});break;case SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT:p(a,"\u6587\u4ef6\u8d85\u8fc710M");break;case SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE:p(a,
"\u6587\u4ef6\u4e0d\u80fd\u4e3a\u7a7a");break;case SWFUpload.QUEUE_ERROR.INVALID_FILETYPE:p(a,"\u6587\u4ef6\u683c\u5f0f\u4e0d\u5bf9")}}catch(e){this.debug(e)}},file_queued_handler:function(a){try{h&&$(".upload_ul").find("li[data-type='error']").remove();var c=a.id;if(10<=$(".upload_ul").find("li").length)$.gs_alert({text:'<p style="color:#066B9F">\u5bf9\u4e0d\u8d77\uff0c\u6700\u591a\u53ea\u53ef\u4e0a\u4f2010\u5f20\u7167\u7247\u3002</p>'});else{var d=$("#"+c);0===d.length&&(a=[],a.push('<li id="'+
c+'">'),a.push(' <i class="delete"></i>'),"ajax"==gsupload.type?a.push(' <span class="speed_load"></span>'):a.push(' <span class="speed-text">0%</span>'),a.push("</li>"),d=$(a.join("")),$(".upload_ul").append(d));l(d);m()}}catch(e){this.debug(e)}},file_dialog_complete_handler:function(a,c){try{this.startUpload(),h=!0}catch(d){this.debug(d)}},upload_progress_handler:function(a,c,d){c=Math.ceil(100*(c/d));$(".upload_ul #"+a.id).find(".speed-text").text(c+"%")},upload_complete_handler:function(a){$(".upload_ul #"+
a.id).find(".speed-text").text("\u5df2\u5b8c\u6210")},upload_success_handler:function(a,c){var d=gsupload.formatdata(c);""==d?$.gs_alert({text:"\u65e0\u6548\u7684\u6570\u636e"}):($(".upload_ul #"+a.id).attr("data-img-id",d.data),d&&($field=$(".upload_ul #"+a.id),$field.find(".speed-text").remove(),$field.find(".speed_load").remove(),$field.append('<img src="'+d.thumbUrl+'">')))}};gsupload.upload(g)});
